# Generated by Django 4.1.1 on 2022-09-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeder',
            name='address',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='first_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is staff'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='is superuser'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is verified'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('ro-ro', 'Romanian'), ('fr', 'French'), ('nl', 'Dutch'), ('de', 'German'), ('it', 'Italian'), ('es', 'Spanish')], default='en-us', max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='last_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='region_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='region state'),
        ),
    ]
