# Generated by Django 4.1.1 on 2022-09-07 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(db_index=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['color'],
            },
        ),
        migrations.CreateModel(
            name='EyeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_color', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Eye color',
                'verbose_name_plural': 'Eye colors',
                'ordering': ['eye_color'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, max_length=15, unique=True)),
                ('in_loft', models.BooleanField()),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator_full_name', models.CharField(max_length=60)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.IntegerField(choices=[(1, 'Short distance'), (2, 'Middle distance'), (3, 'Long distance'), (4, 'Marathon')])),
                ('notes', models.TextField(blank=True, max_length=150, null=True)),
                ('loft', models.ManyToManyField(db_index=True, related_name='strains', to='loft.loft')),
            ],
            options={
                'verbose_name': 'Strain',
                'verbose_name_plural': 'Strains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PigeonLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=30)),
                ('founder_pigeon', models.CharField(max_length=25)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('loft', models.ManyToManyField(db_index=True, related_name='lines', to='loft.loft')),
            ],
            options={
                'verbose_name': 'Pigeon line',
                'verbose_name_plural': 'Pigeon lines',
                'ordering': ['line_name'],
            },
        ),
        migrations.CreateModel(
            name='Pigeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pigeon_organisation', models.CharField(blank=True, max_length=10, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('pigeon_country_code', models.CharField(max_length=10)),
                ('pigeon_ring_number', models.CharField(max_length=10)),
                ('ring_year', models.CharField(max_length=4)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=32)),
                ('hatch_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('section', models.CharField(choices=[('new_entry', 'New Entry'), ('young_bird', 'Young Bird'), ('old_bird', 'Old Bird'), ('breeding', 'Breeding'), ('widow_hen', 'Widow Hen'), ('widow_cock', 'Widow Cock'), ('quarantine', 'Quarantine')], max_length=32)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_best', models.BooleanField(default=False)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('vaccine_date', models.DateField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('other_info', models.TextField(blank=True, max_length=350, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('eye_picture', models.URLField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigeons', to='pigeon.color')),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_childs', to='pigeon.pigeon')),
                ('eye_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigeons', to='pigeon.eyecolor')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pigeons', to='pigeon.pigeonline')),
                ('loft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pigeons', to='loft.loft')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sire_childs', to='pigeon.pigeon')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigeons', to='pigeon.status')),
                ('strain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pigeons', to='pigeon.strain')),
            ],
            options={
                'verbose_name': 'Pigeon',
                'verbose_name_plural': 'Pigeons',
                'ordering': ['loft', 'pigeon_country_code'],
                'unique_together': {('pigeon_country_code', 'pigeon_ring_number', 'pigeon_organisation', 'ring_year')},
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_picture', models.URLField()),
                ('comments', models.TextField(blank=True, max_length=300, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Accepted'), (2, 'Denied')], default=0)),
                ('admin_resolution', models.CharField(blank=True, max_length=500, null=True)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_requests', to=settings.AUTH_USER_MODEL)),
                ('pigeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='pigeon.pigeon')),
            ],
        ),
    ]
