# Generated by Django 4.1.1 on 2022-09-20 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loft', '0002_alter_loft_address_alter_loft_breeder_and_more'),
        ('pigeon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='admin_resolution',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='admin resolution'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='comments',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_requests', to=settings.AUTH_USER_MODEL, verbose_name='initiator'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='pigeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='pigeon.pigeon', verbose_name='pigeon'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='proof_picture',
            field=models.URLField(verbose_name='proof picture'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Accepted'), (2, 'Denied')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='eyecolor',
            name='eye_color',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='eye color'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigeons', to='pigeon.color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='dam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_childs', to='pigeon.pigeon', verbose_name='dam'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='eye_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigeons', to='pigeon.eyecolor', verbose_name='eye color'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='eye_picture',
            field=models.URLField(blank=True, null=True, verbose_name='eye picture'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=32, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='hatch_date',
            field=models.DateField(blank=True, null=True, verbose_name='hatch date'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='is best'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='is hidden'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pigeons', to='pigeon.pigeonline', verbose_name='line'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='loft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pigeons', to='loft.loft', verbose_name='loft'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='other_info',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='other info'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='pigeon_country_code',
            field=models.CharField(max_length=10, verbose_name='pigeon country code'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='pigeon_organisation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pigeon organisation'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='pigeon_ring_number',
            field=models.CharField(max_length=10, verbose_name='pigeon ring number'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='ring_year',
            field=models.CharField(max_length=4, verbose_name='ring year'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='section',
            field=models.CharField(choices=[('new_entry', 'New Entry'), ('young_bird', 'Young Bird'), ('old_bird', 'Old Bird'), ('breeding', 'Breeding'), ('widow_hen', 'Widow Hen'), ('widow_cock', 'Widow Cock'), ('quarantine', 'Quarantine')], max_length=32, verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sire_childs', to='pigeon.pigeon', verbose_name='sire'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigeons', to='pigeon.status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='strain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pigeons', to='pigeon.strain', verbose_name='strain'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='vaccine_date',
            field=models.DateField(blank=True, null=True, verbose_name='vaccine date'),
        ),
        migrations.AlterField(
            model_name='pigeonline',
            name='founder_pigeon',
            field=models.CharField(max_length=25, verbose_name='founder pigeon'),
        ),
        migrations.AlterField(
            model_name='pigeonline',
            name='line_name',
            field=models.CharField(max_length=30, verbose_name='line name'),
        ),
        migrations.AlterField(
            model_name='pigeonline',
            name='loft',
            field=models.ManyToManyField(db_index=True, related_name='lines', to='loft.loft', verbose_name='loft'),
        ),
        migrations.AlterField(
            model_name='pigeonline',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(max_length=7, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='status',
            name='in_loft',
            field=models.BooleanField(verbose_name='in loft'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(db_index=True, max_length=15, unique=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='category',
            field=models.IntegerField(choices=[(1, 'Short distance'), (2, 'Middle distance'), (3, 'Long distance'), (4, 'Marathon')], verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='creator_full_name',
            field=models.CharField(max_length=60, verbose_name='creator full name'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='loft',
            field=models.ManyToManyField(db_index=True, related_name='strains', to='loft.loft', verbose_name='loft'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='notes',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='notes'),
        ),
    ]
