# Generated by Django 4.1.1 on 2022-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0002_alter_claimrequest_admin_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigeon',
            name='gender',
            field=models.CharField(choices=[('MA', 'male'), ('FE', 'female'), ('NN', 'unknown')], max_length=32, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='pigeon',
            name='section',
            field=models.CharField(choices=[('NE', 'new_entry'), ('YB', 'young_bird'), ('OB', 'old_bird'), ('BR', 'breeding'), ('WH', 'widow_hen'), ('WC', 'widow_cock'), ('QT', 'quarantine')], max_length=32, verbose_name='section'),
        ),
    ]
