# Generated by Django 4.1.1 on 2022-09-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0005_alter_pigeon_gender_alter_pigeon_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigeon',
            name='gender',
            field=models.CharField(choices=[(None, 'Select gender'), ('MA', 'Male'), ('FE', 'Female'), ('NN', 'Unknown')], max_length=32, verbose_name='gender'),
        ),
    ]
